spring:
  application:
    name: DomainDriven  # 애플리케이션 이름
  profiles:
    active: docker  # 기본 프로파일을 local로 설정
  datasource:
    name: DomainDrivenDataSource  # 데이터소스 이름
    type: com.zaxxer.hikari.HikariDataSource  # HikariCP 커넥션 풀 사용
    hikari:
      maximum-pool-size: 3  # 최대 커넥션 풀 3개 (개발 환경)
      connection-timeout: 10000  # 10초 커넥션 타임아웃
      max-lifetime: 60000  # 1분 후 커넥션 해제
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false  # OSIV 패턴 비활성화 (성능상 이유)
    generate-ddl: false  # DDL 자동 생성 비활성화
    show-sql: false  # 콘솔에 SQL 쿼리 출력 안함
    hibernate:
      ddl-auto: none  # 하이버네이트 DDL 자동 생성 안함
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC  # UTC 타임존 정규화
      hibernate.jdbc.time_zone: UTC  # JDBC 타임존을 UTC로 설정

---

# 로컬 MySQL 연결 설정 (3306 포트)
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SpringDataBase?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application

---
# 도커 MySQL 연결 설정 (3307 포트)
spring.config.activate.on-profile: docker

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/SpringDataBase?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application
